steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - getPhotoSignedUrl
      - --gen2
      - --project=${PROJECT_ID}
      - --region=${_REGION}
      - --runtime=${_RUNTIME}
      - --source=cloud/google-cloud-functions/getPhotoSignedUrl-function-source
      - --entry-point=getPhotoSignedUrl
      - --service-account=${_SERVICE_ACCOUNT}
      - --set-env-vars=STORAGE_BUCKET=${_STORAGE_BUCKET}
      - --trigger-http
      - --allow-unauthenticated
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - getPhotoSignedUrlsBatch
      - --gen2
      - --project=${PROJECT_ID}
      - --region=${_REGION}
      - --runtime=${_RUNTIME}
      - --source=cloud/google-cloud-functions/getPhotoSignedUrl-function-source
      - --entry-point=getPhotoSignedUrlsBatch
      - --service-account=${_SERVICE_ACCOUNT}
      - --set-env-vars=STORAGE_BUCKET=${_STORAGE_BUCKET}
      - --trigger-http
      - --allow-unauthenticated

substitutions:
  _REGION: us-central1
  _RUNTIME: nodejs22
  _SERVICE_ACCOUNT: coffee-dial-app-9db38@appspot.gserviceaccount.com
  _STORAGE_BUCKET: coffee-dial-app-9db38.firebasestorage.app
